### ISSUE TITLE
make docker_install  error with PATH_SCRIPTS_CONTAINER

### ISSUE THREAD

**Issue by agittins** [calaldees/KaraKara#22]
[support request]
Hi!

First up, this is a pretty impressive project, and great work with the demo / live site as well!

When I run make docker_install, I get https://pastebin.com/6qhQ9jXE of which the important bits seem to be:

`/srv/karakara/docker/scripts_container/_install.sh: line 2: /_shell_environment.sh: No such file or directory
`
and later 

`ImportError: No module named 'setuptools'
`
Re the first error, it looks like this is due to $PATH_SCRIPTS_CONTAINER not being set (I can't find it mentioned anywhere other than the two scripts_container scripts).

Re the second, I have installed pypy_setuptools, python_setuptools and python3_setuptools but it doesn't seem to make a difference (I assume this part isn't running inside a container so relates to my local python but I don't know).

What am I likely to be missing?

I should mention the following changes I made to get this far, in particular the python-version change to match my system version:

(from git diff)

```
+++ b/.env._local
-HOSTNAME=karakara.org.uk
-PATH_HOST_MEDIA=/Users/allan.callaghan/Applications/KaraKara/files
+HOSTNAME=cheshire.home
+PATH_HOST_MEDIA=/srv/media/karaoke

+++ b/docker-compose.yml
-version: '3.5'
+version: '2.0'

[...] 
-            - ${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:ro
+#            - ${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:ro
 
+++ b/website/Makefile
-PYTHON_VERSION:=3.6
+PYTHON_VERSION:=3.5
```

These are obviously local version and path changes (and the google secret caused a .:. mapping which fails), so I doubt they're the problem, although perhaps there's an issue with the python version I have installed.

Any tips you could lend would be much appreciated.

**Comment by calaldees** [comment]
Hi!
It's really exiting to hear that someone else is trying to fire the project up and use it. Welcome aboard!

Thanks for the technical info.
The project is in a bit of a state at the moment. I'm in the middle of transitioning some parts of how the system installs. Some of the unit tests are also failing. I need to reinstate TravisCI. Documentation is outdated and mostly non existent.

I will take a look at your issue in more detail on Friday.
Firstly changing python to 3.5 will probably not work. I'm making heavy use of f'strings.
https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

I will check the docker install works to completion and fix the outstanding unittests.

What is it you are interested in using the system for?
I will probably need to docker-ize processmedia2 to facilitate you encoding your own videos.
I'm happy to talk over Skype or email with you further at somepoint.

**Comment by agittins** [comment]
Thanks for the warm welcome!

No worries re docs, I was fairly warned in the readme that things had changed since :-)

Having a brief look I am wondering if the python stuff is happening inside a container - in which case perhaps we just need to pull in python3.6 in the container rather than linking in the system version. Getting python3.6 on debian 9 is non-trivial and I'd rather not do that to my server - that's what docker's great for  :-)

Ahh, hadn't noticed yet that processmedia wasn't dockerised.

I'm considering using it for my partner's birthday party but it's only a week away so it might not be realistic. It's certainly the most polished and best thought-through system I've found yet, and I love that it's (on it's way to being) fully containerised.

I'll probably have another poke at it tonight and let you know if I make progress, otherwise look forward to hearing from you when you get the time to take a look.

**Comment by calaldees** [comment]
The system can run both inside containers (with postgresql) or in development mode without containers (sqllite). It's not clear in all cases which files are used for each configuration.

If you need it in a week I think the project may not be mature enough for your needs yet.

If you're interested I can give you admin access to the live deployment to setup your own queue and use use it next week. You can also see how the community interface functions.
If you could login with a google account to https://karakara.org.uk/comunity/ (embarrassingly the URL route is misspelled)
After login your avatar will have a yellow "!" beside it as I need to approve you as a user.
Once I've approved you, you can setup your own queue and see the current track dataset. 
The main dataset is for Anime conventions in the UK and has a range of 80's cartoons and games. 
It may be possible to give you sftp access to a folder to upload you own tracks to the server. These will be transcoded and added to the site dataset automatically.

I think using the existing infrastructure this way would be the quickest way to get you up and running for now.

**Comment by calaldees** [comment]
I've had two account requests on karakara.org.uk/comunity/
Neither of these appear to be directly related to your github username.
Could you give me some 'identifying snippets' of the email address you registered so I can approve the correct account.

**Comment by calaldees** [comment]
I've had two account requests on karakara.org.uk/comunity/
Neither of these appear to be directly related to your github username.
Could you give me some 'identifying snippets' of the email address you registered so I can approve the correct account.

**Comment by agittins** [comment]
Howdy! Sorry for the tardiness of my reply - have been fairly busy and needed to have a chat with my partner about how she wanted to proceed with our plans (weighing up roll-our-own vs renting a machine).

We're resolved to going the DIY route, so I'm going to dive in with trying to get this going (but I will probably have a lesser backup plan in place, as this is a lofty goal)!

I've just sent through a request, google@.....au should identify it sufficiently for you :-)

Thanks so very much for your kind offer of using your hosted environment, I'm not sure how realistic it might be though, but perhaps we can discuss that privately. You can contact me at the email address I registered at, but my primary email address (which is by no means private) is ash@ajg.net.au - it would be great to be in direct contact.

**Comment by calaldees** [comment]
I think the latest state of master should get you a little further.
There were multiple problems.

Embarrassingly, some of the variables were misnamed. I'm confused how this ever built before.
https://github.com/calaldees/KaraKara/commit/38b3c465d9323a1b9632ea2ff15e5bb6875a7991

I think I may have also correct an error where incomplete builds of a python _env were leaving residue.
You may need to remove any existing docker volumes realted to karakara as these could be contaminated by the previous incomplete builds.
`docker volume ls`

I was able to run it in dev mode by using `make run` in WindowsSubsystemLinux and the docker containers with `docker-compose run --rm website /srv/karakara/docker/scripts_container/_install.sh` ran to completion, but I have not tested the docker containers further.

Let me know how you progress.

**Comment by shish** [comment]
The whole build system has been redone (minimising makefile use, doing a lot more in the Dockerfile), so this shouldn't be an issue any more
