### ISSUE TITLE
Gracefully handle web clients with `cookies disabled`

### ISSUE THREAD

**Issue by calaldees** [calaldees/KaraKara#25]
We've had clients that have cookies disabled. This create a 'new session event' on every page load.
We maybe should present a message to the user and prevent them from using the site further.

We should potentially try to have nginx redirect back to '/' if a special nginx cookie is not set?
Investigate possible solutions to this problem

**Comment by shish** [comment]
This shouldn't be an issue any more - a client constantly getting new session IDs won't be able to remove a track that they added, but every other feature should work
