### ISSUE TITLE
Load track data into player2 up-front

### ISSUE THREAD

**Issue by shish** [calaldees/KaraKara#62]
90% of `queue_items.json` is track data[1] - if we loaded all of `track_list.json` up-front, and made it so that `queue_items` only contained `track_id` fields to cross-reference, that'd make the updates much smaller

[1] Testing with a 3 hour long queue, `queue_items.json` is 250KB, with track data removed it goes down to 22KB

(This approach would be incompatible with browser1, because browser1 requires that all data to render a single page is fetched in one go, no cross-referencing - so it'd need to happen after browser2 becomes official)

**Comment by calaldees** [comment]
#58 #91 
This ticket proposes loading `track_list.json` into `player2` like `browser2` does.
Track data is now available via a static file (this dramatically improves performance)
when `website` is deprecated, track data will not accessible via a track api.

**Comment by shish** [comment]
This is done now - tracks.json contains all the track data, queue.json only contains track IDs
