### ISSUE TITLE
New `track_list.json` format

### ISSUE THREAD

**Issue by calaldees** [calaldees/KaraKara#91]
`processmedia2` will have a new final step `export_media.py` to output a static file in the following format.

The `track_list.json` format will be changed to something like the following.
```
{
    'BASE62_HASH-TRACKID-11-characters': {
        'source_filename': '',  # For debugging
        'attachments': [
            {
                'url': 'PATH/BASE62_HASH.mp4',
                'use': 'preview',
                'mime': 'video/mp4',
            },
            ## if you want consistent image order then sort by url-string to get consistent order
        ],
        'duration': 300.0,
        'srt': 'SRT_TEXT',
        'tags': 'TAG_TEXT',
    }
}
```

I don't want multiple stages of transforms. I want as few data transforms as possible.

* It is up to the client to parse the SRT.
* It is up to the client to parse the tags.txt.
    * javascript will be provided for translating `tag.txt` into parent/child(s) - this is reasonably trivial.
    * This links/fixes to #21

**Comment by shish** [comment]
tracks.json has a fairly settled format now (see the code for the exact format, it's not exactly what was written here)
